apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: app-ingress
  namespace: dev
  annotations:
    ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: loja.test
    http:
      paths:
      - path: /
        backend:
          serviceName: app
          servicePort: 80
